services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: crisis_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: crisisconnect
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - postgres_password
  
secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

volumes:
  pgdata: